config/routes.rb
Rails.application.routes.draw do
  
  root to: 'main#index'

  resources :user_sessions, only: [:create, :new, :destroy]

  resources :password_resets, only: [:new, :create, :edit, :update]
  
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  
  match ':controller(/:action(/:id))', :via => [:get, :post]
  

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(user_session_params)
    if @user_session.save
      flash[:success] = "Welcome #{current_user.name}!"
      redirect_to root_path
    else
      show_flash_error(@user_session)
      render :new
    end
  end

  def destroy
    if current_user_session
      current_user_session.destroy
      flash[:success] = "See you!"
    end
    redirect_to root_path
  end

  private

  def user_session_params
    params.require(:user_session).permit(:username, :password, :remember_me)
  end

  def set_page_title
    @page_title = "Session"
  end

end

app/views/user_sessions/new.html.erb
<%= form_for @user_session do |f| %>

<h3>Log in</h3>

<div class="row">
  <div class="col-sm-4 form-group">
    <%= f.text_field :username, class: 'form-control', placeholder: :username %>
  </div>
</div>

<div class="row">
  <div class="col-sm-4 form-group">  
    <%= f.password_field :password, class: 'form-control', placeholder: :password %>
  </div>
</div>

<div class="form-buttons confirm-buttons">
  <%= f.button "<span class='glyphicon glyphicon-ok' aria-hidden='true'></span> Log in".html_safe, :class => 'btn btn-success' %>
</div>

<div class="row">
  <div class="col-sm-4 forgot-pass">  
    <%= link_to '>> Forgot your password?', new_password_reset_path %>
  </div>
</div>

<% end %>